version: '3'
services:
  blockly-playground:
    image: blockly-playground:latest
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    stdin_open: true
    tty: true
    network_mode: host
    # ports: 
    #   - 8888:8888
      # - 11311:11311
    privileged: true
    # user: root
    # user: jovyan
    # working_dir: /home/jovyan/
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    entrypoint: ["/home/jovyan/blockly-playground/binder/entrypoint.sh"]
    volumes:
      - ../:/home/jovyan/blockly-playground:rw
      - ${HOST_GISKARD_WS}:/home/jovyan/workspace/ros/src/giskardpy
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # environment:
      # - DISPLAY
    #   - QT_X11_NO_MITSHM=1
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
